#!/usr/bin/env node
import "../bootstrap.js";
import { createHash } from "node:crypto";
import pg from "pg"; import mysql from "mysql2/promise";
const pairs={"1B":"1A.2","2A":"2A.1","2B":"2A.2","3A":"3A.1","4A":"4A.1","4B":"4A.2","5B":"5A.2","6A":"6A.1","8A":"8A.1","9A":"9A.1","23A":"23A.1","25A":"25A.1"};
const pgc=new pg.Client(process.env.DATABASE_URL||{host:process.env.PGHOST,port:+(process.env.PGPORT||5432),database:process.env.PGDATABASE,user:process.env.PGUSER,password:process.env.PGPASSWORD});
const my=await mysql.createConnection({host:process.env.MYSQL_HOST,port:+(process.env.MYSQL_PORT||3306),database:process.env.MYSQL_DATABASE||process.env.MYSQL_DB,user:process.env.MYSQL_USER,password:process.env.MYSQL_PASSWORD||process.env.MYSQL_PASS}); await pgc.connect();
const point=(r,k)=>{const x=Number(r[`${k}Easting`]),y=Number(r[`${k}Northing`]);return Number.isFinite(x)&&Number.isFinite(y)&&x!==0?[x,y,Number(r[`${k}Aod`])]:null};
const polygon=(r,keys)=>{const pts=keys.map(k=>point(r,k));return pts.some(p=>!p)?null:`POLYGON((${[...pts,pts[0]].map(p=>`${p[0]} ${p[1]}`).join(',')}))`};
const legacyHeight=(r,t)=>{const a=point(r,'a'),b=point(r,'b');const l2=Math.hypot(b[0]-a[0],b[1]-a[1]),l1=l2*t,l3=l2-l1;const az=a[2]-.0673*(l1/1000)**2,bz=b[2]-.0673*(l3/1000)**2;return az+t*(bz-az)};
try { await pgc.query('BEGIN'); const [rows]=await my.query('SELECT * FROM lvmf ORDER BY viewRef'); const raw=JSON.stringify(rows);const sha=createHash('sha256').update(raw).digest('hex');let q=await pgc.query(`INSERT INTO lvmf_legacy_snapshots(snapshot_label,source_sha256,rows_json) VALUES('legacy-mysql-viewer-2026-09-13',$1,$2::jsonb) ON CONFLICT(snapshot_label) DO UPDATE SET source_sha256=EXCLUDED.source_sha256,rows_json=EXCLUDED.rows_json RETURNING id`,[sha,raw]);const snap=q.rows[0].id;
q=await pgc.query(`SELECT id FROM lvmf_2026_datasets WHERE version_label='2026-consultation-draft'`);const dataset=q.rows[0].id;await pgc.query('DELETE FROM lvmf_legacy_comparison_matches WHERE dataset_id=$1 AND snapshot_id=$2',[dataset,snap]);const byRef=new Map(rows.map(r=>[r.viewRef,r]));
for(const [next,old] of Object.entries(pairs)){const r=byRef.get(old);if(!r)continue;q=await pgc.query(`INSERT INTO lvmf_legacy_comparison_matches(dataset_id,snapshot_id,new_view_code,legacy_view_ref) VALUES($1,$2,$3,$4) RETURNING id`,[dataset,snap,next,old]);const match=q.rows[0].id;for(const [code,keys] of [['vc',['a','c','d']],['llaa',['a','v','c']],['rlaa',['a','w','d']],['baa',point(r,'v')&&point(r,'w')?['v','w','z','y']:['c','d','z','y']]]){const wkt=polygon(r,keys);if(wkt)await pgc.query(`INSERT INTO lvmf_legacy_comparison_areas(match_id,area_code,geom) VALUES($1,$2,ST_GeomFromText($3,27700))`,[match,code,wkt]);}
const metrics=await pgc.query(`SELECT la.area_code,ST_Area(la.geom) legacy_area,ST_Area(ca.geom) current_area,ST_Area(ST_Intersection(la.geom,ca.geom)) inter,ST_Area(ST_Union(la.geom,ca.geom)) uni,ST_Area(ST_SymDifference(la.geom,ca.geom)) sym,ST_HausdorffDistance(la.geom,ca.geom) haus FROM lvmf_legacy_comparison_areas la JOIN lvmf_legacy_comparison_matches m ON m.id=la.match_id JOIN lvmf_2026_views v ON v.dataset_id=$1 AND v.view_code=m.new_view_code JOIN lvmf_2026_areas ca ON ca.view_id=v.id AND ca.area_code=la.area_code WHERE la.match_id=$2`,[dataset,match]);const currentPts=await pgc.query(`SELECT point_code,ST_X(geom)x,ST_Y(geom)y,ST_Z(geom)z FROM lvmf_2026_control_points p JOIN lvmf_2026_views v ON v.id=p.view_id WHERE v.dataset_id=$1 AND v.view_code=$2`,[dataset,next]);const cp=Object.fromEntries(currentPts.rows.map(p=>[p.point_code,p]));const profile=[0,.25,.5,.75,1].map(t=>({station:t,legacy_m_aod:legacyHeight(r,t),current_m_aod:(()=>{const a=cp.a,d=cp.d,l2=Math.hypot(d.x-a.x,d.y-a.y),l1=l2*t,l3=l2-l1,az=a.z-.0673*(l1/1000)**2,bz=d.z-.0673*(l3/1000)**2;return az+t*(bz-az)})()}));for(const m of metrics.rows)await pgc.query(`INSERT INTO lvmf_legacy_comparison_results(match_id,area_code,legacy_area_m2,current_area_m2,intersection_m2,union_m2,jaccard,symmetric_difference_m2,hausdorff_m,height_profile_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb)`,[match,m.area_code,m.legacy_area,m.current_area,m.inter,m.uni,m.uni?m.inter/m.uni:null,m.sym,m.haus,JSON.stringify(profile)]);
} const legacyOnly=byRef.get('2B.1');if(legacyOnly){q=await pgc.query(`INSERT INTO lvmf_legacy_comparison_matches(dataset_id,snapshot_id,new_view_code,legacy_view_ref,confidence) VALUES($1,$2,$3,$4,'legacy_only') RETURNING id`,[dataset,snap,'__legacy_only_2B.1','2B.1']);for(const [code,keys] of [['vc',['a','c','d']],['llaa',['a','v','c']],['rlaa',['a','w','d']],['baa',point(legacyOnly,'v')&&point(legacyOnly,'w')?['v','w','z','y']:['c','d','z','y']]]){const wkt=polygon(legacyOnly,keys);if(wkt)await pgc.query(`INSERT INTO lvmf_legacy_comparison_areas(match_id,area_code,geom) VALUES($1,$2,ST_GeomFromText($3,27700))`,[q.rows[0].id,code,wkt]);}} await pgc.query('COMMIT');console.log(JSON.stringify({success:true,matches:Object.keys(pairs).length,unmatched_legacy:['2B.1'],unmatched_new:['25B']},null,2)); }catch(e){await pgc.query('ROLLBACK');throw e}finally{await my.end();await pgc.end();}
